name: cristoapp
description: Aplicativo Cristão com Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/biblia_nvi/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/jesus.png"
  min_sdk_android: 21  # Adiciona a versão mínima para Android.
  remove_alpha_ios: true  # Remove o canal alfa nos ícones do iOS.
